# These tasks are included once per shipyard_stack

- name: "Gather some facts about {{ shipyard_stack.name }}"
  set_fact:
    chart_path: "{{ shipyard_charts_path }}/{{ shipyard_stack.chart }}"
    stack_remote_path: "/opt/shipyard/stacks/{{ shipyard_stack.name }}"
    # Lookup default values from the Chart
    default_values: "{{ lookup('file', '{{ shipyard_charts_path }}/{{ shipyard_stack.chart }}/values.yaml') | from_yaml }}"
    # Lookup values from the Stack
    stack_values: "{{ lookup('file', '{{shipyard_stacks_path}}/{{ shipyard_stack.name }}/values.yaml', errors='ignore') | from_yaml | default({}, true) }}"
    stack_values_sops: "{{ lookup('community.sops.sops', '{{shipyard_stacks_path}}/{{ shipyard_stack.name }}/values.sops.yaml', errors='ignore') | from_yaml | default({}, true) }}"

- name: "Gather the {{ shipyard_stack.name }} values"
  set_fact:
    values: "{{ default_values | combine(stack_values, recursive=true) | combine(stack_values_sops, recursive=true) }}"

- name: "Debug {{ shipyard_stack.name }} combined values"
  ansible.builtin.debug:
    var: values

- name: Ensure remote stack directory for {{ shipyard_stack.name }}
  become: true
  ansible.builtin.file:
    path: "{{ stack_remote_path }}"
    state: directory
    mode: '0700'

- name: Print directories that will be present in the {{ shipyard_stack.name }} stack directory
  ansible.builtin.debug:
    msg: 'directory: {{ stack_remote_path }}/{{ item.path }}; mode: {{ item.mode }}'
    verbosity: 1
  with_community.general.filetree: '{{ chart_path }}/templates/'
  when: item.state == 'directory'

- name: Directories are present in the {{ shipyard_stack.name }} stack directory
  become: true
  ansible.builtin.file:
    path: '{{ stack_remote_path }}/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_community.general.filetree: '{{ chart_path }}/templates/'
  when: item.state == 'directory'

- name: Print templated files that will be present in the {{ shipyard_stack.name }} stack directory
  become: true
  ansible.builtin.debug:
    msg: 'file: {{ stack_remote_path }}/{{ item.path }}; mode: {{ item.mode }}'
    verbosity: 1
  with_community.general.filetree: '{{ chart_path }}/templates/'
  when: item.state == 'file'

- name: Templated files are present in the {{ shipyard_stack.name }} stack directory
  become: true
  vars:
    # Define two top-level (hence the uppercase first character - just like Helm) variables to use in the templates
    Stack: '{{ shipyard_stack }}'
    Values: '{{ values }}'
  ansible.builtin.template:
    src: '{{ chart_path }}/templates/{{ item.path }}'
    dest: '{{ stack_remote_path }}/{{ item.path }}'
    mode: u=rw,g=r,o=r
  with_community.general.filetree: '{{ chart_path }}/templates/'
  when: item.state == 'file'

- name: Docker volumes for {{ shipyard_stack.name }} are pesent in the swarm
  become: true
  community.docker.docker_volume:
    name: '{{ item.name }}'
    state: present
  loop: '{{ values.primed_volumes | default([]) }}'

- name: Docker volumes for {{ shipyard_stack.name }} are primed
  become: true
  ansible.builtin.shell:
    cmd: 'tar --directory={{ stack_remote_path }}/{{ item.path }} --create --file=- . | docker run --rm --interactive --volume {{ item.name }}:/data alpine tar --directory=/data --extract --verbose --file=- && touch {{ stack_remote_path }}/{{ item.path }}/.done'
    creates: '{{ stack_remote_path }}/{{ item.path }}/.done'
  loop: '{{ values.primed_volumes | default([]) }}'

- name: Docker secrets are present
  become: true
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: "{{ item.data | b64encode }}"
    data_is_b64: true
    state: present
  loop: "{{ shipyard_stacks_docker_secrets|default([]) }}"

- name: Deploy shipyard stack
  become: true
  docker_stack:
    name: "{{ shipyard_stack.name }}"
    state: present
    with_registry_auth: true
    compose:
      - "{{ stack_remote_path }}/docker-compose.yml"
