---
- name: "Set default shipyard_filename"
  set_fact:
    shipyard_filename: "{{ inventory_dir }}/shipyard.yaml"
  when: shipyard_filename is undefined

- name: "Set default shipyard_charts_path"
  set_fact:
    shipyard_charts_path: "{{ inventory_dir }}/shipyard/charts"
  when: shipyard_charts_path is undefined

- name: "Set default shipyard_stacks_path"
  set_fact:
    shipyard_stacks_path: "{{ inventory_dir }}/shipyard/stacks"
  when: shipyard_stacks_path is undefined

- name: "Shipyard config"
  set_fact:
    shipyard_config: "{{ lookup('file', '{{ shipyard_filename }}') | from_yaml }}"

- name: "Stackfile debug"
  ansible.builtin.debug:
    msg: "{{ shipyard_config }}"

- name: "Initialize empty shipyard_stacks array"
  set_fact:
    shipyard_stacks: []

- name: "Load shipyard stacks for this host"
  set_fact:
    shipyard_stacks: "{{ shipyard_stacks + [item] }}"
  loop: "{{ shipyard_config.stacks }}"
  when: item.host == inventory_hostname

- name: "Debug: shipyard.stacks"
  ansible.builtin.debug:
    msg: "{{ shipyard_stacks }}"

- name: "Deploy shipyard stacks"
  include_tasks: deploy-stack.yml
  loop: "{{ shipyard_stacks }}"
  loop_control:
    label: "Deploy stack: [{{ shipyard_stack.name }}]"
    loop_var: shipyard_stack
